### ISSUE TITLE
Not working on FreeNas (9.3-STABLE-201509220011)

### ISSUE THREAD

**Issue by rubenverhoef** [jedediahfrey/FreeNAS-Gitlab#2]
First of all, when i run the script it cannot find gitlab.sql so i edited gitlab_root.sh with the path: /FreeNAS-Gitlab/gitlab.sql

after that the installation ended "succesfully" with 
![capture](https://cloud.githubusercontent.com/assets/9071284/10073740/70cfe9ca-62cb-11e5-8877-1ae1acd758f4.PNG)

when i go to the ip i get a gitlab 502 error.
i cannot start the gitlab service, when i start it "service gitlab start" i get weird messages and the user is switched to git:

root@gitlab_1:/FreeNAS-Gitlab # service gitlab start
Need to do a search in a manpage or in a file you've sent to a pager? Use
"/search_word". To repeat the same search, type "n" for next.
                -- Dru <genesis@istar.ca>
[git@gitlab_1 ~]$

**Comment by lellimecnar** [comment]
Same here

**Comment by jedediahfrey** [comment]
Project is no longer maintained. There are 2 forks, you could try asking those authors:

https://github.com/jedediahfrey/FreeNAS-Gitlab/network/members

**Comment by rubenverhoef** [comment]
great tip! using gogs now! :)
